#! /usr/bin/env python3

import os
import time

from methods.bcolors import bcolors
from methods.add import write
from methods.clean import remove_duplicate


# get total path to this file
filepath = os.path.abspath(os.path.dirname(__file__))

# Start menu >>>>>
print(bcolors.HEADER + '\n-------- Texup: backup manager by GTex --------' + bcolors.ENDC)
print('1. Full backup')
print('2. Save new/changed folders and files')
print('3. Delete old folder and files')
print('0. Exit')

# get user input for option
while True:
    user_input = int(input('\nOption: '))
    if user_input < 0 or user_input > 3:
        print(bcolors.FAIL + 'Not a valid option!' + bcolors.ENDC)
    else:
        break

# run backup
if user_input == 1:
    print(bcolors.HEADER + '\nStep 1: Save new/changed folders and files...' + bcolors.ENDC)
    write(filepath)
    print(bcolors.HEADER + '\nStep 2: Delete old folders and files...' + bcolors.ENDC)
    remove_duplicate(filepath)
elif user_input == 2:
    print(bcolors.HEADER + '\nSave new/changed folders and files...' + bcolors.ENDC)
    write(filepath)
elif user_input == 3:
    print(bcolors.HEADER + '\nDelete old folder and files...' + bcolors.ENDC)
    remove_duplicate(filepath)

print("\nThanks for using Texup!")
time.sleep(2)
# <<<<< End menu