#! /usr/bin/env python3
import sys
import datetime
import time
import webbrowser
import random
import numpy as np

def get_timer_input():
    hour = int(input('----TIMER----\nhours: '))
    min = int(input('minutes: '))
    sec = int(input('seconds: '))
    return hour, min, sec

def check_time(end):
    now = datetime.datetime.now()
    dif = end-now
    if end > now:
        print(f'TIME:   {str(dif).split(".")[0]}', end='\r')
    else:
        print('TIME:    00:00:00')
    return now>=end

def get_url():
    with open('/home/gtex/scripts/timer/urls.txt') as f:
        lines = f.readlines()
    return random.choice(lines)
    

# set timer
# check for arguments
arg = sys.argv[1:]
if len(arg)==3:
    hour = int(arg[0])
    min = int(arg[1])    
    sec = int(arg[2])    
else:
    hour, min, sec = get_timer_input() # time as user input

rest_time = datetime.timedelta(hours=hour, minutes=min, seconds=sec)

end = datetime.datetime.now() + rest_time

size = np.random.poisson(lam=10)
while True:
    if check_time(end):
        for _ in range(size):
            print(_*'RIINGGG!! ')
        for _ in reversed(range(size)):
            print(_*'RIINGGG!! ')
        url = get_url()
        webbrowser.open(url)
        break
    time.sleep(1) #check time every second